Repository OneKonsole/web-service-frontend, pull requests merged in 2023-11, with the labels that each got.

#42 feat: init and add sidebar
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.tsx
  src/assets/base.css
  src/assets/react.svg
  src/components/SideBar.tsx
  src/icons/account.svg
  src/icons/billing.svg
  src/icons/cluster.svg
  src/icons/download.svg
  src/icons/logos/logo-full.svg
  src/icons/logos/logo-short.svg
  src/icons/logout.svg
  src/icons/monitor.svg
  src/icons/order.svg
  src/index.css
  src/main.tsx
  src/pages/[...all].tsx
  src/pages/auth/login.tsx
  src/pages/auth/logout.tsx
  src/pages/auth/test/[id].jsx
  src/pages/menus/account.tsx
  src/pages/menus/billing.tsx
  src/pages/menus/clusters.tsx
  src/pages/menus/download.tsx
  src/pages/menus/monitor.tsx
  src/pages/menus/order.tsx
  tailwind.config.js
Labels: Dev

#45 feat: Integrate download page
  src/assets/icons/Game.svg
  src/assets/icons/disc.svg
  src/components/inputs/Button.tsx
  src/pages/account/index.tsx
  src/pages/auth/forgot-password.tsx
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/download/index.tsx
  src/pages/menus/download.tsx
Labels: Integ, Design

#46 feat: add order page
  index.html
  public/logo-short.svg
  public/vite.svg
  src/assets/icons/api.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/cm.svg
  src/assets/icons/etcd.svg
  src/assets/icons/scheduler.svg
  src/assets/logos/graphana-loki.svg
  src/assets/logos/prometheus.svg
  src/components/SideBar.tsx
  src/components/inputs/Button.tsx
  src/components/inputs/InfraSchema.tsx
  src/components/inputs/InputField.tsx
  src/components/inputs/RangeSlider.tsx
  src/components/inputs/ToggleSwitch.tsx
  src/components/layout/PanelLayout.tsx
  src/pages/menus/order.tsx
  src/pages/order/index.tsx
  src/type.ts
  tailwind.config.js
Labels: Dev, Design

#47 feature : billing page and fix side bar
  package.json
  src/App.tsx
  src/assets/icons/arrow-right-2.svg
  src/assets/icons/chevron-down.svg
  src/assets/icons/chevron-up.svg
  src/assets/icons/credit-card-dark.svg
  src/assets/icons/credit-card-gold.svg
  src/assets/icons/download-cloud.svg
  src/assets/icons/download.svg
  src/assets/icons/edit.svg
  src/assets/logos/paypal-full.svg
  src/components/SideBar.tsx
  src/components/billing/PaymentAddress.tsx
  src/components/billing/PaymentDisplay.tsx
  src/components/billing/PaymentHistory.tsx
  src/components/billing/PaymentHistoryInstance.tsx
  src/components/billing/PaymentMethod.tsx
  src/components/inputs/InfraSchema.tsx
  src/components/layout/PanelLayout.tsx
  src/components/layout/SideBarContext.tsx
  src/pages/account/index.tsx
  src/pages/auth/login.tsx
  src/pages/billing/index.tsx
  src/pages/menus/billing.tsx
  src/pages/order/index.tsx
  src/requests/billingRequests.ts
  src/requests/userInfoRequests.ts
  src/type.ts
  src/utils/BillingHelper.ts
  src/utils/DateHelper.ts
  tailwind.config.js
  vite.config.ts
Labels: Dev, Design
